servers: 
  - port: 8004
    host: localhost
    queries:
      - outputWriters:
          - "@class": com.googlecode.jmxtrans.model.output.StatsDWriter
            port: 8787
            host: localhost
        obj: java.lang:type=OperatingSystem
        attr: 
          - SystemLoadAverage
          - FreePhysicalMemorySize
          - FreeSwapSpaceSize
          - OpenFileDescriptorCount
    numQueryThreads" : 2
